[workspace]
resolver = "2"
members = [
    "kpcodec",
    "kpserver",
    "kpscene",
    "kpapp",
    "examples/plugin/memory_wasm",
    "examples/plugin/text",
    "examples/plugin/kplayer-plugin-sdk",
]
