use kpcodec::filter::filter::KPFilter;
use kpcodec::filter::graph::KPGraph;
use crate::scene::scene::KPScene;
use anyhow::Result;
use anyhow::anyhow;
use std::collections::{BTreeMap, HashMap};
use std::env;
use log::info;
use rusty_ffmpeg::ffi::AV_PIX_FMT_YUV420P;
use kpcodec::decode::decode::KPDecode;
use kpcodec::encode::encode::KPEncode;
use kpcodec::filter::graph::KPGraphStatus;
use kpcodec::util::alias::{KPAVMediaType, KPAVPixelFormat, KPAVSampleFormat};
use kpcodec::util::encode_parameter::KPEncodeParameter;
use crate::init::initialize;
use std::fs;
use rusty_ffmpeg::ffi::{AV_SAMPLE_FMT_FLTP};
use kpcodec::util::codec_status::KPCodecStatus;
use crate::scene::engine::wasm::KPEngine;
use crate::scene::scene::KPSceneSortType;

mod scene;
mod graph;
mod engine;